CIFRAS.Presentation/Controllers/BancoController.cs
using CIFRAS.Application.Interfaces;
using CIFRAS.Application.ViewModel;
using CIFRAS.Infra.CrossCutting.Helpers;
using CIFRAS.Presentation.Helpers.DataTables.Filter;
using System;
using System.Web.Mvc;

namespace CIFRAS.Presentation.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class BancoController : Controller
    {
        private readonly IBancoAppService _bancoApp;

        public BancoController(IBancoAppService bancoApp)
        {
            _bancoApp = bancoApp;
        }

        public ActionResult ObterTabela(int draw, int start, int length)
        {
            string searchValue = Request.QueryString["search[value]"];
            string orderColumn = Request.QueryString["order[0][column]"];
            string orderDir = Request.QueryString["order[0][dir]"];
            var dataTable = new BancoFilter(_bancoApp).ProcessFilter(draw, start, length, searchValue, orderColumn, orderDir);
            return Json(dataTable, JsonRequestBehavior.AllowGet);
        }
        
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Adicionar()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Adicionar(BancoVm model)
        {
            try
            {
                if (!ModelState.IsValid) throw new Exception();
                _bancoApp.Adicionar(model);
                return RedirectToAction("Index").Success();
            }
            catch (Exception e)
            {
                return View(model).Error(e.Message);
            }
        }

        public ActionResult Editar(int id)
        {
            var model = _bancoApp.BuscarPorId(id);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(BancoVm model)
        {
            try
            {
                if (!ModelState.IsValid) throw new Exception();
                _bancoApp.Atualizar(model);
                return RedirectToAction("Index").Success();
            }
            catch (Exception e)
            {
                return View(model).Error(e.Message);
            }
        }

        public ActionResult Remover(int id)
        {
            try
            {
                _bancoApp.Remover(new BancoVm { BancoId = id });
                return RedirectToAction("Index").Success();
            }
            catch (Exception e)
            {
                return RedirectToAction("Index").Error(e.Message);
            }
        }
    }
}

CIFRAS.Presentation/Controllers/ClienteController.cs
using CIFRAS.Application.Interfaces;
using CIFRAS.Application.ViewModel;
using CIFRAS.Infra.CrossCutting.Helpers;
using CIFRAS.Presentation.Helpers.DataTables.Filter;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace CIFRAS.Presentation.Controllers
{
    [Authorize]
    public class ClienteController : Controller
    {
        private readonly IClienteAppService _clienteApp;
        private readonly IBancoAppService _bancoApp;
        private readonly ITipoClienteAppService _tipoClienteApp;
        private readonly ITipoContratoAppService _tipoContratoApp;

        public ClienteController(IClienteAppService clienteApp, IBancoAppService bancoApp, ITipoClienteAppService tipoClienteApp, ITipoContratoAppService tipoContratoApp)
        {
            _clienteApp = clienteApp;
            _bancoApp = bancoApp;
            _tipoClienteApp = tipoClienteApp;
            _tipoContratoApp = tipoContratoApp;
        }

        public ActionResult ObterTabela(int draw, int start, int length, FiltroClienteVm model)
        {
            string searchValue = Request.QueryString["search[value]"];
            string orderColumn = Request.QueryString["order[0][column]"];
            string orderDir = Request.QueryString["order[0][dir]"];
            var dataTable = new ClienteFilter(_clienteApp).ProcessFilter(draw, start, length, searchValue, orderColumn, orderDir, model);
            return Json(dataTable, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Index()
        {
            SetViewBagTipoCliente();
            return View();
        }

        public ActionResult Adicionar()
        {
            TempData["Contas"] = null;
            TempData["Contratos"] = null;
            TempData["Contatos"] = null;
            SetViewBag();
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Adicionar(ClienteVm model)
        {
            try
            {
                if (!ModelState.IsValid) throw new Exception();
                model.ValidarRmc();
                model.ListaConta = TempData["Contas"] as ICollection<ContaVm> ?? new List<ContaVm>();
                model.ListaContrato = TempData["Contratos"] as ICollection<ContratoVm> ?? new List<ContratoVm>();
                model.ListaContato = TempData["Contatos"] as ICollection<ContatoVm> ?? new List<ContatoVm>();
                if (_clienteApp.PermitirInserir(model.Cpf, model.NumeroMatricula)) _clienteApp.Adicionar(model);
                return RedirectToAction("Index").Success();
            }
            catch (Exception e)
            {
                SetViewBag();
                return View(model).Error(e.Message);
            }
        }

        public ActionResult Editar(int id)
        {
            var model = _clienteApp.BuscarPorIdCustomizado(id);
            TempData["Contas"] = model.ListaConta;
            TempData["Contratos"] = model.ListaContrato;
            TempData["Contatos"] = model.ListaContato;
            SetViewBag();
            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(ClienteVm model)
        {
            try
            {
                if (!ModelState.IsValid) throw new Exception();
                model.ListaConta = TempData["Contas"] as ICollection<ContaVm> ?? new List<ContaVm>();
                model.ListaContrato = TempData["Contratos"] as ICollection<ContratoVm> ?? new List<ContratoVm>();
                model.ListaContato = TempData["Contatos"] as ICollection<ContatoVm> ?? new List<ContatoVm>();
                _clienteApp.Atualizar(model);
                return RedirectToAction("Index").Success();
            }
            catch (Exception e)
            {
                SetViewBag();
                return View(model).Error(e.Message);
            }
        }

        public ActionResult Remover(int id)
        {
            try
            {
                _clienteApp.Remover(new ClienteVm { ClienteId = id });
                return RedirectToAction("Index").Success();
            }
            catch (Exception e)
            {
                return RedirectToAction("Index").Error(e.Message);
            }
        }

        public ActionResult Detalhes(int id)
        {
            var cliente = _clienteApp.BuscarPorIdBasico(id);
            cliente.SetarDataVisualizacao();
            _clienteApp.Atualizar(cliente);
            SetViewBagTipoCliente();
            var model = _clienteApp.BuscarPorIdCustomizado(id);           
            return View(model);
        }

        [HttpPost]
        public ActionResult AdicionarConta(ContaVm model)
        {
            var list = TempData["Contas"] as IList<ContaVm> ?? new List<ContaVm>();
            model.BancoView = _bancoApp.BuscarPorId(model.BancoId ?? 0).Descricao;
            list.Add(model);
            TempData["Contas"] = list;
            TempData.Keep("Contas");
            SetViewBagTipoCliente();
            return View("Index");
        }

        public JsonResult RemoverConta(int index)
        {
            try
            {
                var list = TempData["Contas"] as IList<ContaVm>;
                list.RemoveAt(index);
                TempData["Contas"] = list;
                TempData.Keep("Contas");
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(e.Message, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult AtualizarContas()
        {
            var lista = TempData["Contas"] as IList<ContaVm> ?? new List<ContaVm>();
            TempData.Keep("Contas");
            return PartialView("_ListaConta", lista);
        }

        [HttpPost]
        public ActionResult AdicionarContrato(ContratoVm model)
        {
            var list = TempData["Contratos"] as IList<ContratoVm> ?? new List<ContratoVm>();
            model.BancoView = _bancoApp.BuscarPorId(model.BancoId ?? 0).Descricao;
            model.TipoContratoView = _tipoContratoApp.BuscarPorId(model.TipoContratoId).Descricao;
            list.Add(model);
            TempData["Contratos"] = list;
            TempData.Keep("Contratos");
            SetViewBagTipoCliente();
            return View("Index");
        }

        public JsonResult RemoverContrato(int index)
        {
            try
            {
                var list = TempData["Contratos"] as IList<ContratoVm>;
                list.RemoveAt(index);
                TempData["Contratos"] = list;
                TempData.Keep("Contratos");
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(e.Message, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult AtualizarContratos()
        {
            var lista = TempData["Contratos"] as IList<ContratoVm> ?? new List<ContratoVm>();
            TempData.Keep("Contratos");
            return PartialView("_ListaContrato", lista);
        }

        [HttpPost]
        public ActionResult AdicionarContato(ContatoVm model)
        {
            var list = TempData["Contatos"] as IList<ContatoVm> ?? new List<ContatoVm>();
            list.Add(model);
            TempData["Contatos"] = list;
            TempData.Keep("Contatos");
            SetViewBagTipoCliente();
            return View("Index");
        }

        public JsonResult RemoverContato(int index)
        {
            try
            {
                var list = TempData["Contatos"] as IList<ContatoVm>;
                list.RemoveAt(index);
                TempData["Contatos"] = list;
                TempData.Keep("Contatos");
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(e.Message, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult AtualizarContatos()
        {
            var lista = TempData["Contatos"] as IList<ContatoVm> ?? new List<ContatoVm>();
            TempData.Keep("Contatos");
            return PartialView("_ListaContato", lista);
        }

        public JsonResult BuscarCliente(int id)
        {
            var model = _clienteApp.BuscarPorId(id);
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Imprimir(int id)
        {
            var model = _clienteApp.BuscarPorIdCustomizado(id);
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public void SetViewBag()
        {
            ViewBag.Bancos = _bancoApp.BuscarTodos();
            ViewBag.TiposClientes = _tipoClienteApp.BuscarTodos();
            ViewBag.TiposContratos = _tipoContratoApp.BuscarTodos();
        }

        public void SetViewBagTipoCliente()
        {
            ViewBag.TiposClientes = _tipoClienteApp.BuscarTodos();
        }
    }
}

CIFRAS.Presentation/Controllers/ReciboController.cs
using CIFRAS.Application.Interfaces;
using CIFRAS.Application.ViewModel;
using CIFRAS.Infra.CrossCutting.Helpers;
using CIFRAS.Presentation.Helpers.DataTables.Filter;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace CIFRAS.Presentation.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class ReciboController : Controller
    {
        private readonly IBancoAppService _bancoApp;
        private readonly ITipoClienteAppService _tipoClienteApp;
        private readonly ICorretorAppService _corretorApp;
        private readonly IReciboAppService _reciboApp;

        public ReciboController(IBancoAppService bancoApp, ITipoClienteAppService tipoClienteApp, ICorretorAppService corretorApp, IReciboAppService reciboApp)
        {
            _bancoApp = bancoApp;
            _tipoClienteApp = tipoClienteApp;
            _corretorApp = corretorApp;
            _reciboApp = reciboApp;
        }

        public ActionResult ObterTabela(int draw, int start, int length)
        {
            var searchValue = Request.QueryString["search[value]"];
            var orderColumn = Request.QueryString["order[0][column]"];
            var orderDir = Request.QueryString["order[0][dir]"];
            var dataTable = new ReciboFilter(_reciboApp).ProcessFilter(draw, start, length, searchValue, orderColumn, orderDir);
            return Json(dataTable, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Adicionar()
        {
            TempData["ReciboEmprestimo"] = null;
            SetViewBag();
            return View();
        }

        [HttpPost]
        public ActionResult Adicionar(ReciboVm model)
        {
            try
            {
                if (!ModelState.IsValid) throw new Exception();
                model.ListaReciboEmprestimo = TempData["ReciboEmprestimo"] as ICollection<ReciboEmprestimoVm> ?? new List<ReciboEmprestimoVm>();
                _reciboApp.Adicionar(model);
                return RedirectToAction("Index").Success();
            }
            catch (Exception e)
            {
                SetViewBag();
                return View(model).Error(e.Message);
            }
        }

        public ActionResult Editar(int id)
        {
            var model = _reciboApp.BuscarPorIdCustomizado(id);
            TempData["ReciboEmprestimo"] = model.ListaReciboEmprestimo;
            SetViewBag();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(ReciboVm model)
        {
            try
            {
                if (!ModelState.IsValid) throw new Exception();
                model.ListaReciboEmprestimo = TempData["ReciboEmprestimo"] as ICollection<ReciboEmprestimoVm> ?? new List<ReciboEmprestimoVm>();
                _reciboApp.Atualizar(model);
                return RedirectToAction("Index").Success();
            }
            catch (Exception e)
            {
                SetViewBag();
                return View(model).Error(e.Message);
            }
        }

        public ActionResult Download(int id)
        {
            var model = _reciboApp.BuscarPorIdCustomizado(id);
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult AdicionarEmprestimo(ReciboEmprestimoVm model)
        {
            var list = TempData["ReciboEmprestimo"] as IList<ReciboEmprestimoVm> ?? new List<ReciboEmprestimoVm>();
            model.BancoView = _bancoApp.BuscarPorId(model.BancoId).Descricao;
            model.TipoClienteView = _tipoClienteApp.BuscarPorId(model.TipoClienteId).Descricao;
            list.Add(model);
            TempData["ReciboEmprestimo"] = list;
            TempData.Keep("ReciboEmprestimo");
            SetViewBag();
            return View("Index");
        }

        public JsonResult RemoverReciboEmprestimo(int index)
        {
            try
            {
                var list = TempData["ReciboEmprestimo"] as IList<ReciboEmprestimoVm>;
                list.RemoveAt(index);
                TempData["ReciboEmprestimo"] = list;
                TempData.Keep("ReciboEmprestimo");
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(e.Message, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult AtualizarEmprestimos()
        {
            var lista = TempData["ReciboEmprestimo"] as IList<ReciboEmprestimoVm> ?? new List<ReciboEmprestimoVm>();
            TempData.Keep("ReciboEmprestimo");
            return PartialView("_ListaReciboEmprestimo", lista);
        }

        public ActionResult Remover(int id)
        {
            try
            {
                _reciboApp.Remover(new ReciboVm { ReciboId = id });
                return RedirectToAction("Index").Success();
            }
            catch (Exception e)
            {
                return RedirectToAction("Index").Error(e.Message);
            }
        }

        public void SetViewBag()
        {
            ViewBag.Bancos = _bancoApp.BuscarTodos();
            ViewBag.TiposClientes = _tipoClienteApp.BuscarTodos();
            ViewBag.Corretores = _corretorApp.BuscarTodos();
        }
    }
}

CIFRAS.Presentation/Views/Shared/_ButtonForm.cshtml
<div class="row">
    <div class="col-md-12 mb-3">
        <button type="submit" class="btn btn-primary">Salvar</button>
        <button type="reset" class="btn btn-danger">Limpar</button>
    </div>
</div>

CIFRAS.Presentation/Views/Shared/_Footer.cshtml
<footer class="sticky-footer">
    <div class="container">
        <div class="text-center">
            <small>Todos os direitos reservados © CIFRAS PROMOTORA @DateTime.Now.Year - Versão 1.1.1</small>
        </div>
    </div>
</footer>

CIFRAS.Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title - CIFRAS Promotora</title>  
    @Styles.Render("~/Content/basic-vendor")
    @Styles.Render("~/Content/basic-css")
    @RenderSection("styles", required: false)
</head>

<body class="fixed-nav sticky-footer bg-dark" id="page-top">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
        <a class="navbar-brand" href="@Url.Action("Index", "Home")">CIFRAS PROMOTORA</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            @Html.Action("LayoutMenu", "Permissao")
            @Html.Action("LayoutTop", "Permissao")            
        </div>
    </nav>
    <div class="content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    @RenderBody()
                </div>
            </div>
        </div>
        @Html.Partial("_Footer")
        @Html.Partial("_ModalSair")
        @Html.Action("ModalPerfil", "Permissao")     
        @Scripts.Render("~/bundles/basic-vendor")
        @Scripts.Render("~/bundles/basic-js")
        @RenderSection("scripts", required: false)
        @Html.Partial("_Message")
    </div>
</body>
</html>

CIFRAS.Presentation/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Autenticação - CIFRAS Promotora</title>
    @Styles.Render("~/Content/basic-vendor")
    @Styles.Render("~/Content/basic-css")
    @RenderSection("styles", required: false)
</head>
<body class="bg-dark">
    <div class="container">
        <div class="card card-login mx-auto mt-5">
            <div class="card-header">Login</div>
            <div class="card-body">
                @RenderBody()
            </div>
        </div>
    </div>  
    @Scripts.Render("~/bundles/basic-vendor")
    @Scripts.Render("~/bundles/basic-js")
    @RenderSection("scripts", required: false)
    @Html.Partial("_Message")
</body>
</html>

CIFRAS.Presentation/Views/Shared/_LayoutMenu.cshtml
@using CIFRAS.Application.ViewModel
@model FuncionarioVm

<ul class="navbar-nav navbar-sidenav">

    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Página Inicial">
        <a class="nav-link" href="@Url.Action("Index", "Home")">
            <i class="fa fa-fw fa-home"></i>
            <span class="nav-link-text">Página Inicial</span>
        </a>
    </li>

    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Clientes">
        <a class="nav-link" href="@Url.Action("Index", "Cliente")">
            <i class="fa fa-fw fa-user-circle"></i>
            <span class="nav-link-text">Clientes</span>
        </a>
    </li>

    @if (Model.Cargo == Cargo.Administrador)
    {
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Recibos">
            <a class="nav-link" href="@Url.Action("Index", "Recibo")">
                <i class="fa fa-fw fa-download"></i>
                <span class="nav-link-text">Recibos</span>
            </a>
        </li>

        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Bancos">
            <a class="nav-link" href="@Url.Action("Index", "Banco")">
                <i class="fa fa-fw fa-bank"></i>
                <span class="nav-link-text">Bancos</span>
            </a>
        </li>

        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Corretores">
            <a class="nav-link" href="@Url.Action("Index", "Corretor")">
                <i class="fa fa-fw fa-briefcase"></i>
                <span class="nav-link-text">Corretores</span>
            </a>
        </li>

        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Funcionários">
            <a class="nav-link" href="@Url.Action("Index", "Funcionario")">
                <i class="fa fa-fw fa-user-plus"></i>
                <span class="nav-link-text">Funcionários</span>
            </a>
        </li>

        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Importação">
            <a class="nav-link" href="@Url.Action("Index", "Importacao")">
                <i class="fa fa-fw fa-upload"></i>
                <span class="nav-link-text">Importação</span>
            </a>
        </li>

        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tipos de Cliente">
            <a class="nav-link" href="@Url.Action("Index", "TipoCliente")">
                <i class="fa fa-fw fa-star"></i>
                <span class="nav-link-text">Tipos de Cliente</span>
            </a>
        </li>

        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tipos de Contrato">
            <a class="nav-link" href="@Url.Action("Index", "TipoContrato")">
                <i class="fa fa-fw fa-star"></i>
                <span class="nav-link-text">Tipos de Contrato</span>
            </a>
        </li>

        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Categoria de Arquivos">
            <a class="nav-link" href="@Url.Action("Index", "CategoriaArquivo")">
                <i class="fa fa-fw fa-star"></i>
                <span class="nav-link-text">Categoria de Arquivos</span>
            </a>
        </li>
    }

</ul>

CIFRAS.Presentation/Views/Shared/_LayoutTop.cshtml
@using CIFRAS.Application.ViewModel
@model FuncionarioVm

<ul class="navbar-nav sidenav-toggler">
    <li class="nav-item">
        <a class="nav-link text-center" id="sidenavToggler">
            <i class="fa fa-fw fa-angle-left"></i>
        </a>
    </li>
</ul>

<ul class="navbar-nav ml-auto">
    <li class="nav-item">
        <a class="nav-link" data-toggle="modal" data-target="#modalPerfil">
            <i class="fa fa-fw fa-user"></i>
            @Model.Nome
        </a>        
    </li>
    <li class="nav-item">
        <a class="nav-link" data-toggle="modal" data-target="#modalSair">           
            <i class="fa fa-fw fa-sign-out"></i>Sair
        </a>
    </li>
</ul>

CIFRAS.Presentation/Views/Shared/_Message.cshtml
@using CIFRAS.Infra.CrossCutting.Helpers
@{
    var alerts = TempData.ContainsKey("Message") ? (List<Alert>)TempData["Message"] : new List<Alert>();
    if (alerts.Any())
    {
        <script>
            @{
               foreach (var item in alerts)
               {
                   @Html.Raw("swal('Mensagem','" + item.Message + "', '" + item.AlertStyle + "')")
               }
           }
        </script>
    }
}

CIFRAS.Presentation/Views/Shared/_ModalPerfil.cshtml
@using CIFRAS.Application.ViewModel
@model FuncionarioVm

<div class="modal fade" id="modalPerfil" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Perfil</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="Nome">Nome</label>
                    <input type="text" class="form-control" id="Nome" value="@Model.Nome" disabled="">                   
                </div>
                <div class="form-group">
                    <label for="Cpf">CPF</label>
                    <input type="text" class="form-control" id="Cpf" value="@Model.Cpf" disabled="">
                </div>
                <div class="form-group">
                    <label for="Cargo">Cargo</label>
                    <input type="text" class="form-control" id="Cargo" value="@Model.Cargo" disabled="">
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

CIFRAS.Presentation/Views/Shared/_ModalSair.cshtml
<div class="modal fade" id="modalSair" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Atenção</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Deseja realmente sair?</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Não</button>
                <a class="btn btn-primary" href="@Url.Action("Sair", "Funcionario")">Sim</a>
            </div>
        </div>
    </div>
</div>

CIFRAS.Presentation/Views/Shared/_TitleForm.cshtml
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a id="title" href="@Url.Action("Index")">@ViewBag.Title</a>
    </li>
    <li class="breadcrumb-item active">@ViewBag.Subtitle</li>
</ol>