CIFRAS.Presentation/Controllers/FuncionarioController.cs
using CIFRAS.Application.Interfaces;
using CIFRAS.Application.ViewModel;
using CIFRAS.Infra.CrossCutting.Helpers;
using CIFRAS.Presentation.Helpers.DataTables.Filter;
using System;
using System.Web.Mvc;

namespace CIFRAS.Presentation.Controllers
{
    public class FuncionarioController : Controller
    {
        private readonly IFuncionarioAppService _funcionarioApp;

        public FuncionarioController(IFuncionarioAppService funcionarioApp)
        {
            _funcionarioApp = funcionarioApp;
        }

        public ActionResult Logar()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Logar(LoginVm model)
        {
            try
            {
                if (!ModelState.IsValid) throw new Exception();
                bool validarUsuario = _funcionarioApp.ValidarLogin(model.Login, model.Senha);
                if (validarUsuario)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    return Redirect("Logar").Error("Login ou senha inválidos!");
                }
            }
            catch (Exception e)
            {
                return Redirect("Logar").Error(e.Message);
            }
        }

        public ActionResult Sair()
        {
            try
            {
                _funcionarioApp.DesconectarUsuario();
                return Redirect("Logar").Success("Desconectado com sucesso!");
            }
            catch (Exception e)
            {
                return Redirect("Logar").Error(e.Message);
            }
        }
        
        public ActionResult ObterTabela(int draw, int start, int length)
        {
            string searchValue = Request.QueryString["search[value]"];
            string orderColumn = Request.QueryString["order[0][column]"];
            string orderDir = Request.QueryString["order[0][dir]"];
            var dataTable = new FuncionarioFilter(this._funcionarioApp).ProcessFilter(draw, start, length, searchValue, orderColumn, orderDir);
            return Json(dataTable, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Administrador")]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Administrador")]
        public ActionResult Adicionar()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Adicionar(FuncionarioVm model)
        {
            try
            {
                if (!ModelState.IsValid) throw new Exception();
                _funcionarioApp.Adicionar(model);
                return RedirectToAction("Index").Success();
            }
            catch (Exception e)
            {
                return View(model).Error(e.Message);
            }
        }

        [Authorize(Roles = "Administrador")]
        public ActionResult Editar(int id)
        {
            var model = _funcionarioApp.BuscarPorId(id);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(FuncionarioVm model)
        {
            try
            {
                if (!ModelState.IsValid) throw new Exception();
                _funcionarioApp.Atualizar(model);
                return RedirectToAction("Index").Success();
            }
            catch (Exception e)
            {
                return View(model).Error(e.Message);
            }
        }

        [Authorize(Roles = "Administrador")]
        public ActionResult Remover(int id)
        {
            try
            {
                _funcionarioApp.Remover(new FuncionarioVm { FuncionarioId = id });
                return RedirectToAction("Index").Success();
            }
            catch (Exception e)
            {
                return RedirectToAction("Index").Error(e.Message);
            }
        }
    }
}

CIFRAS.Presentation/Views/Funcionario/Adicionar.cshtml
@model CIFRAS.Application.ViewModel.FuncionarioVm
@{
    ViewBag.Title = "Funcionário";
    ViewBag.Subtitle = "Novo";
}

@Html.Partial("_TitleForm")

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.Partial("_Form")
    @Html.Partial("_ButtonForm")
}

CIFRAS.Presentation/Views/Funcionario/Editar.cshtml
@model CIFRAS.Application.ViewModel.FuncionarioVm
@{
    ViewBag.Title = "Funcionário";
    ViewBag.Subtitle = "Editar";
}

@Html.Partial("_TitleForm")

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.FuncionarioId)
    @Html.Partial("_Form")
    @Html.Partial("_ButtonForm")
}

CIFRAS.Presentation/Views/Funcionario/Index.cshtml
@using CIFRAS.Infra.CrossCutting.Helpers
@{
    ViewBag.Title = "Funcionários";
    ViewBag.Subtitle = "Todos";
}

@section styles{
    @Styles.Render("~/Content/datatables-css")
}

@Html.Partial("_TitleForm")

<div class="card mb-3">
    <div class="card-header">
        @Html.TableButton("btn btn-success", "fa fa-lg fa-plus", "Novo", Url.Action("Adicionar"))
        @Html.TableButton("btn btn-info", "fa fa-lg fa-refresh", "Atualizar", Url.Action("Index"))
    </div>
    <div class="card-body">
        <div class="table-responsive">
            @Html.Partial("_Tabela")
        </div>
    </div>
    <div class="card-footer small text-muted">Atualizado em @DateTime.Now</div>
</div>

@section scripts{
    @Scripts.Render("~/bundles/datatables-js")
    @Scripts.Render("~/bundles/funcionario-table-js")
}

CIFRAS.Presentation/Views/Funcionario/Logar.cshtml
@model CIFRAS.Application.ViewModel.LoginVm
@{
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.Partial("_FormLogin")
}

CIFRAS.Presentation/Views/Funcionario/_Form.cshtml
@model CIFRAS.Application.ViewModel.FuncionarioVm

<div class="row">
    <div class="col-lg-12">
        <div class="card mb-3">
            <div class="card-header">Geral</div>
            <div class="card-body">
                <div class="row">
                    <div class="form-group col-md-4">
                        @Html.LabelFor(m => m.Nome)
                        @Html.EditorFor(m => m.Nome, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.Nome)
                    </div>

                    <div class="form-group col-md-2">
                        @Html.LabelFor(m => m.Cpf)
                        @Html.EditorFor(m => m.Cpf, new { htmlAttributes = new { @class = "form-control cpf" } })
                        @Html.ValidationMessageFor(m => m.Cpf)
                    </div>

                    <div class="form-group col-md-2">
                        @Html.LabelFor(m => m.Cargo)
                        @Html.EnumDropDownListFor(m => m.Cargo, "Selecione...", new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Cargo)
                    </div>

                    <div class="form-group col-md-2">
                        @Html.LabelFor(m => m.Login)
                        @Html.EditorFor(m => m.Login, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.Login)
                    </div>

                    <div class="form-group col-md-2">
                        @Html.LabelFor(m => m.Senha)
                        @Html.EditorFor(m => m.Senha, new { htmlAttributes = new { @class = "form-control", type = "password" } })
                        @Html.ValidationMessageFor(m => m.Senha)
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

CIFRAS.Presentation/Views/Funcionario/_FormLogin.cshtml
@model CIFRAS.Application.ViewModel.LoginVm

<div class="form-group">
    @Html.EditorFor(m => m.Login, new { htmlAttributes = new { @class = "form-control", placeholder = "Login" } })
    @Html.ValidationMessageFor(m => m.Login)
</div>

<div class="form-group">
    @Html.EditorFor(m => m.Senha, new { htmlAttributes = new { @class = "form-control", placeholder = "Senha", type = "password" } })
    @Html.ValidationMessageFor(m => m.Senha)
</div>

<input type="submit" class="btn btn-primary btn-block" value="Acessar">

CIFRAS.Presentation/Views/Funcionario/_Tabela.cshtml
@using CIFRAS.Infra.CrossCutting.Helpers
@{
    ViewBag.TableUrl = Url.Content("~/Funcionario/ObterTabela").ToAbsoluteUrl();
    ViewBag.TranslatorUrl = Url.Content("~/Scripts/vendor/datatables/translator.json").ToAbsoluteUrl();
    ViewBag.EditBtnUrl = Url.Action("Editar", "Funcionario");
    ViewBag.RemoveBtnUrl = Url.Action("Remover", "Funcionario");
}

<table id="datatable" data-edit="@ViewBag.EditBtnUrl" data-remove="@ViewBag.RemoveBtnUrl" data-table="@ViewBag.TableUrl" data-translator="@ViewBag.TranslatorUrl" data-plugin="DataTable" class="table table-bordered table-striped table-hover" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>Nome</th>
            <th>CPF</th>
            <th>Cargo</th>
            <th>Ação</th>
        </tr>
    </thead>
</table>