CIFRAS.Presentation/Controllers/TipoContratoController.cs
using CIFRAS.Application.Interfaces;
using CIFRAS.Application.ViewModel;
using CIFRAS.Infra.CrossCutting.Helpers;
using CIFRAS.Presentation.Helpers.DataTables.Filter;
using System;
using System.Web.Mvc;

namespace CIFRAS.Presentation.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class TipoContratoController : Controller
    {
        private readonly ITipoContratoAppService _tipoContratoApp;

        public TipoContratoController(ITipoContratoAppService tipoContratoApp)
        {
            _tipoContratoApp = tipoContratoApp; 
        }

        public ActionResult ObterTabela(int draw, int start, int length)
        {
            string searchValue = Request.QueryString["search[value]"];
            string orderColumn = Request.QueryString["order[0][column]"];
            string orderDir = Request.QueryString["order[0][dir]"];
            var dataTable = new TipoContratoFilter(_tipoContratoApp).ProcessFilter(draw, start, length, searchValue, orderColumn, orderDir);
            return Json(dataTable, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Adicionar()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Adicionar(TipoContratoVm model)
        {
            try
            {
                if (!ModelState.IsValid) throw new Exception();
                _tipoContratoApp.Adicionar(model);
                return RedirectToAction("Index").Success();
            }
            catch (Exception e)
            {
                return View(model).Error(e.Message);
            }
        }

        public ActionResult Editar(int id)
        {
            var model = _tipoContratoApp.BuscarPorId(id);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(TipoContratoVm model)
        {
            try
            {
                if (!ModelState.IsValid) throw new Exception();
                _tipoContratoApp.Atualizar(model);
                return RedirectToAction("Index").Success();
            }
            catch (Exception e)
            {
                return View(model).Error(e.Message);
            }
        }

        public ActionResult Remover(int id)
        {
            try
            {
                _tipoContratoApp.Remover(new TipoContratoVm { TipoContratoId = id });
                return RedirectToAction("Index").Success();
            }
            catch (Exception e)
            {
                return RedirectToAction("Index").Error(e.Message);
            }
        }
    }
}

CIFRAS.Presentation/Views/TipoContrato/Adicionar.cshtml
@model CIFRAS.Application.ViewModel.TipoContratoVm
@{
    ViewBag.Title = "Tipo de Contrato";
    ViewBag.Subtitle = "Novo";
}

@Html.Partial("_TitleForm")

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.Partial("_Form")
    @Html.Partial("_ButtonForm")
}

CIFRAS.Presentation/Views/TipoContrato/Editar.cshtml
@model CIFRAS.Application.ViewModel.TipoContratoVm
@{
    ViewBag.Title = "Tipo de Contrato";
    ViewBag.Subtitle = "Editar";
}

@Html.Partial("_TitleForm")

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.TipoContratoId)
    @Html.Partial("_Form")
    @Html.Partial("_ButtonForm")
}

CIFRAS.Presentation/Views/TipoContrato/Index.cshtml
@using CIFRAS.Infra.CrossCutting.Helpers
@{
    ViewBag.Title = "Tipos de Contrato";
    ViewBag.Subtitle = "Todos";
}

@section styles{
    @Styles.Render("~/Content/datatables-css")
}

@Html.Partial("_TitleForm")

<div class="card mb-3">
    <div class="card-header">
        @Html.TableButton("btn btn-success", "fa fa-lg fa-plus", "Novo", Url.Action("Adicionar"))
        @Html.TableButton("btn btn-info", "fa fa-lg fa-refresh", "Atualizar", Url.Action("Index"))
    </div>
    <div class="card-body">
        <div class="table-responsive">
            @Html.Partial("_Tabela")
        </div>
    </div>
    <div class="card-footer small text-muted">Atualizado em @DateTime.Now</div>
</div>

@section scripts{
    @Scripts.Render("~/bundles/datatables-js")
    @Scripts.Render("~/bundles/tipo-contrato-table-js")
}

CIFRAS.Presentation/Views/TipoContrato/_Form.cshtml
@model CIFRAS.Application.ViewModel.TipoContratoVm

<div class="row">
    <div class="col-lg-12">
        <div class="card mb-3">
            <div class="card-header">Geral</div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12 mb-3">
                        @Html.LabelFor(m => m.Descricao)
                        @Html.EditorFor(m => m.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.Descricao)
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

CIFRAS.Presentation/Views/TipoContrato/_Tabela.cshtml
@using CIFRAS.Infra.CrossCutting.Helpers
@{
    ViewBag.TableUrl = Url.Content("~/TipoContrato/ObterTabela").ToAbsoluteUrl();
    ViewBag.TranslatorUrl = Url.Content("~/Scripts/vendor/datatables/translator.json").ToAbsoluteUrl();
    ViewBag.EditBtnUrl = Url.Action("Editar", "TipoContrato");
    ViewBag.RemoveBtnUrl = Url.Action("Remover", "TipoContrato");
}

<table id="datatable" data-edit="@ViewBag.EditBtnUrl" data-remove="@ViewBag.RemoveBtnUrl" data-table="@ViewBag.TableUrl" data-translator="@ViewBag.TranslatorUrl" data-plugin="DataTable" class="table table-bordered table-hover" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>Descrição</th>
            <th>Ação</th>
        </tr>
    </thead>
</table>